language: node_js
install:
  - npm install -g codecov
node_js:
  - "stable"
before_script:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - codecov
on:
  branch: master
